
import { createContext } from "react";


export const LanguageContext = createContext<any>({})


export const Thesaurus = {
    english:{
        Welcome:{
            title:"Our solution to your problem!",
            description: "We give you more control over your appointements, while also ridding you of unnecessary wait time!",
            googleBtn: "Sign in with Google!",
            button: "Hi, Start with War9a!"    
        },
        queueDetails:{
            // these were in multiple objects that were repeatedly called in multiple pages
            join: "join",
            categories:["Doctor", "Barber", "Food", "Other"],
            time: ["MINS", "HRS", "DAYS", "MTHS"],
            inqueueTitle:"in queue",
            serviceLocation:"",
        },
        MainHub:{
            locationBtn:"Current Location",
            location:["City", "Code"],
            searchTitle:"Search...",
            filtersBtn:"Filters",
            availableTitle:"Available Services",
            allBtn:"See All",
            inviteTitle:"Invite a friend",
            inviteDesc:"Get Rewards",
            inviteBtn:"INVITE",
        },
        Navigation:{
            exploreBtn:"Explore",
            queuesBtn:"My Queues",
            favoritesBtn:"Favorites",
            profileBtn:"Profile",
        },
        ServicePage:{
            inviteBtn:"Invite",
            serviceName:"",
            joined: "Joined",
            Months:["January","February","March","April","May","June","July","August","September","October","Novermber","December"],
            open:"Open",
            weekDays:["Saturday","Sunday","Monday","Tuesday","Wednesday","Thursday","Friday"],
            locationTitle:"Location",
            location:"",
            contactBtn:"Contact",
            aboutTitle:"About",
            about:"",
        },
        serviceQueue:{
            serviceName:"",
            queueTab:"QUEUE",
            detailsTab:"DETAILS",
            emptyTitle:"Queue is empty",
            emptyDesc:"Interested by this service? Claim the first position in this queue.",
            enterBtn:"ENTER QUEUE",
            tpc: "TPC",
            addedInfo: ["Self added", "Added by service provider"],
            leaveBtn: "LEAVE QUEUE",
        },
        serviceDetails:{
            serviceName:"",
            queueTab:"QUEUE",
            detailsTab:"DETAILS",
            joinedTitle:"Joined",
            joinedValue:"",
            locationTitle:"Location",
            locationValue:"",
            queueTitle:"People in Queue",
            queueValue:["There are","people in queue"],
            waitingTitle:"Estimated waiting time",
            waitingValue:["seconds", "minutes", "hours", "days", "weeks", "months", "N/A"],
            ratingTitle:"Rating",
            ratingValue:"Avg.",
            favoritedTitle:"Favorited",
            favoritedValue:["Favorited by", "users"],
            visitedTitle:"Visited",
            visitedValue:["Visited by","users"],          
        },
        searchFilters: {
            timeTitle:"Time & Date",
            timeValues: ["Today", "Tomorrow", "This Week", "This Month", "Choose from Calendar"],
            locationTitle:"Location",
            locationValue:["Within", "K", "M", "Km"],
            resetTbn:"RESET",
            applyBtn:"APPLY",
        },
        profile:{
            Developer:"Developer",
            profileSettings: {
                title:"Profile Settings",
                edit: "Edit Profile",
            },
            appSettings: {
                title:"App Settings",
                notifications:"Notifications",
                languages:"Language",
            },
            moreInformation: {
                title:"More Informations",
                registerService: "Become a partner service",
                terminate: "Terminate your service",
                customerService: "Customer Service",
                review:"Write us a review",
                contact:"Contact Us",
                disconnect: "Logout",
            }
        },
    },
    french:{
        Welcome:{
            title:"Notre solution à votre problème!",
            description: "Prenez plus de contrôle sur vos rendez-vous, débarrassez vous du temps d'attente unitile!",
            googleBtn: "Se connecter avec Google!",
            button: "Salut, Commencez avec War9a!"    
        },
        queueDetails:{
            join:"rejoindre",
            categories:["Médecin","Coiffeur","Nourriture","Autre"],
            time: ["MINS", "HRS", "JRS", "MOIS"],
            inqueueTitle:"dans la queue",
            serviceLocation:"",
        },
        MainHub:{
            locationBtn:"Votre Emplacement",
            location:["City", "Code"],
            searchTitle:"Rechercher...",
            filtersBtn:"Filtres",
            availableTitle:"Services Disponibles",
            allBtn:"Voir Tout",
            inviteTitle:"Inviter un ami",
            inviteDesc:"Récompenses",
            inviteBtn:"INVITER",
        },
        Navigation:{
            exploreBtn:"Explorer",
            queuesBtn:"Mes queues",
            favoritesBtn:"Favoris",
            profileBtn:"Profil",
        },
        ServicePage:{
            inviteBtn:"Inviter",
            serviceName:"",
            joined: "Rejoint",
            Months:["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"],
            open:"Ouvert",
            weekDays:["Samedi", "Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
            locationTitle:"Emplacement",
            location:"",
            contactBtn:"Contacter",
            aboutTitle:"A propos",
            about:"",
        },
        serviceQueue:{
            serviceName:"",
            queueTab:"QUEUE",
            detailsTab:"DETAILS",
            emptyTitle:"La queue est vide",
            emptyDesc:"intéréssé par ce service? Réclamez la première position dans cette queue.",
            enterBtn:"REJOINDRE QUEUE",
            tpc: "TPC",
            addedInfo: ["Self added", "Ajouté par le propriétaire du service"],
            leaveBtn: "QUITTER LA QUEUE",
        },
        serviceDetails:{
            serviceName:"",
            queueTab:"QUEUE",
            detailsTab:"DETAILS",
            joinedTitle:"Rejoint",
            joinedValue:"",
            locationTitle:"Emplacement",
            locationValue:"",
            queueTitle:"Personnes dans la Queue",
            queueValue:["Il y a","personnes dans cette queue"],
            waitingTitle:"Temps d'attente estimé",
            waitingValue:["secondes", "minutes", "heures", "jours", "semaines", "mois", "N/A"],
            ratingTitle:"Evaluation",
            ratingValue:"Moy.",
            favoritedTitle:"Favori",
            favoritedValue:["Favori par", "utilisateurs"],
            visitedTitle:"Visité",
            visitedValue:["Visité par","utilisateurs"],          
        },
        searchFilters: {
            timeTitle:"Date & Heure",
            timeValues: ["Aujourdhui", "Demain", "Semaine", "Ce Mois", "Choose from Calendar"],
            locationTitle:"Emplacement",
            locationValue:["à", "K", "M", "Km"],
            resetTbn:"REINITIALISER",
            applyBtn:"APPLIQUER",
        },
        profile:{
            Developer:"Développeur",
            profileSettings: {
                title:"Paramètres du profil",
                edit: "Modifier votre profil",
            },
            appSettings: {
                title:"Paramètres de l'application",
                notifications:"Notifications",
                languages:"Langue",
            },
            moreInformation: {
                title:"Plus d'information",
                registerService: "Devenir un service partenaire",
                terminate: "Résiliez votre service",
                customerService: "Service Client",
                review:"Ecrivez-nous votre avis",
                contact:"Contactez Nous",
                disconnect: "Se déconnecter",
            }
        }
    },
    arabic:{
        Welcome:{
            title:"دعنا نحل مشكلتك",
            description: "تحكم في مواعيدك، تخلص وقت الانتظار الغير الضروري",
            googleBtn: " Google! تسجيل الدخول باستعمال",
            button: "war9a مرحباً ، ابدأ باستعمال"
        },
        queueDetails:{
            // these were in multiple objects that were repeatedly called in multiple pages
            join: "انضم",
            categories:["طبيب", "حلاق", "طعام", "حدمات أخرى"],
            time: ["د", "سا", "أيام", "ش"],
            inqueueTitle:"ينتظرون دورهم",
            serviceLocation:"",
        },
        MainHub:{
            locationBtn:"موقعك الحالي",
            location:["مدينة", "رمز"],
            searchTitle:"...ابحـث",
            filtersBtn:"اعدادات البحـث",
            availableTitle:"الخدمات المتواجدة",
            allBtn:"اظهار الكل",
            inviteTitle:"دعوة صديق",
            inviteDesc:"احصل على مكافآت",
            inviteBtn:"دعوة",
        },
        Navigation:{
            exploreBtn:"استطلاع",
            queuesBtn:"طوابيري",
            favoritesBtn:"المفضلة",
            profileBtn:"بروفايل",
        },
        ServicePage:{
            inviteBtn:"دعوة",
            serviceName:"",
            joined: "تاريخ الانضمام",
            Months:["جانفي" , "فيفري" , "مارس" , "أفريل" , "ماي" , "جوان" , "جويلية" , "أوت" , "سبتمبر" , "أكتوبر" , "نوفمبر" , "ديسمبر"],
            open:"يعمل الان",
            weekDays:["السبت","الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة"],
            locationTitle:"الموقع",
            location:"",
            contactBtn:"اتصل بصاحب الخدمة",
            aboutTitle:"حول",
            about:"",
        },
        serviceQueue:{
            serviceName:"",
            queueTab:"طابور",
            detailsTab:"معلومات",
            emptyTitle:"طابور فارغ",
            emptyDesc:"هذا الطابور فارغ. يمكنك المرور بدون انتظار",
            enterBtn:"أدخل في الطابور",
            tpc: "TPC",
            addedInfo: ["دخل بنفسه", "أضافه صاحب الخدمة"],
            leaveBtn: "الخروج من الطابور",
        },
        serviceDetails:{
            serviceName:"",
            queueTab:"طابور",
            detailsTab:"معلومات",
            joinedTitle:"تاريخ الانضمام",
            joinedValue:"",
            locationTitle:"الموقع",
            locationValue:"",
            queueTitle:"أشخاص في الطابور",
            queueValue:["يوجد","شخص ينتظرون دورهم"],
            waitingTitle:"وقت الانتظار المتوقع",
            waitingValue:["ثواني", "دقائق", "ساعات", "أيام", "أسابيع", "أشهر", "N/A"],
            ratingTitle:"التقييم",
            ratingValue:"Avg.",
            favoritedTitle:"المفضل",
            favoritedValue:["مفضل من طرف", "شخص"],
            visitedTitle:"الزيارات",
            visitedValue:["زيارة من طرف","شخص"],          
        },
        searchFilters: {
            timeTitle:"وقت وتاريخ",
            timeValues: ["اليوم", "يوم غد", "هذا الأسبوع", "هذا الشهر", "اختر وقتاً آخر"],
            locationTitle:"الموقع",
            locationValue:["في", "ألف", "متر", "كم"],
            resetTbn:"مسح واعادة",
            applyBtn:"تطبيق",
        },
        profile:{
            Developer:"مبرمج",
            profileSettings: {
                title:"اعدادات البروفايل",
                edit: "تعديل البروفايل",
            },
            appSettings: {
                title:"إعدادات التطبيق",
                notifications:"الإشعارات",
                languages:"اللغة",
            },
            moreInformation: {
                title:"المزيد من المعلومات",
                registerService: "كن شريكًا في الخدمة",
                terminate: "الغـاء الاشتراك",
                customerService: "خدمة الزبائن",
                review:"قم بكتابة تقييمك",
                contact:"اتصل بنـا",
                disconnect: "الخـروج",
            }
        }
    }
}